### YamlMime:ManagedReference
items:
- uid: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient
  id: IEnvironmentClient
  parent: Picturepark.SDK.V1.CloudManager.Contract
  children:
  - Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync(System.Threading.CancellationToken)
  - Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync(System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: IEnvironmentClient
  nameWithType: IEnvironmentClient
  fullName: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient
  type: Interface
  source:
    remote:
      path: src/Picturepark.SDK.V1.CloudManager/Generated/Contracts.Generated.cs
      branch: release-prep/PP9-21763-regenerate-docs
      repo: https://github.com/Picturepark/Picturepark.SDK.DotNet
    id: IEnvironmentClient
    path: ../../src/Picturepark.SDK.V1.CloudManager/Generated/Contracts.Generated.cs
    startLine: 768
  assemblies:
  - Picturepark.SDK.V1.CloudManager
  namespace: Picturepark.SDK.V1.CloudManager.Contract
  syntax:
    content: >-
      [GeneratedCode("NSwag", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))")]

      public interface IEnvironmentClient
    content.vb: >-
      <GeneratedCode("NSwag", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))")>

      Public Interface IEnvironmentClient
  attributes:
  - type: System.CodeDom.Compiler.GeneratedCodeAttribute
    ctor: System.CodeDom.Compiler.GeneratedCodeAttribute.#ctor(System.String,System.String)
    arguments:
    - type: System.String
      value: NSwag
    - type: System.String
      value: 13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))
- uid: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync(System.Threading.CancellationToken)
  commentId: M:Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync(System.Threading.CancellationToken)
  id: CreateAsync(System.Threading.CancellationToken)
  parent: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient
  langs:
  - csharp
  - vb
  name: CreateAsync(CancellationToken)
  nameWithType: IEnvironmentClient.CreateAsync(CancellationToken)
  fullName: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync(System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/Picturepark.SDK.V1.CloudManager/Generated/Contracts.Generated.cs
      branch: release-prep/PP9-21763-regenerate-docs
      repo: https://github.com/Picturepark/Picturepark.SDK.DotNet
    id: CreateAsync
    path: ../../src/Picturepark.SDK.V1.CloudManager/Generated/Contracts.Generated.cs
    startLine: 781
  assemblies:
  - Picturepark.SDK.V1.CloudManager
  namespace: Picturepark.SDK.V1.CloudManager.Contract
  example: []
  syntax:
    content: Task<EnvironmentConfiguration> CreateAsync(CancellationToken cancellationToken = default)
    parameters:
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: A cancellation token that can be used by other objects or threads to receive notice of cancellation.
    return:
      type: System.Threading.Tasks.Task{Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration}
    content.vb: Function CreateAsync(cancellationToken As CancellationToken = Nothing) As Task(Of EnvironmentConfiguration)
  overload: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync*
  exceptions:
  - type: Picturepark.SDK.V1.CloudManager.Contract.ApiException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.ApiException
    description: A server side error occurred.
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
    description: Validation exception
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
    description: Forbidden
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
    description: Version conflict
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
    description: Too many requests
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    description: Internal server error
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    description: Entity not found
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
    description: Entity not found
- uid: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync(System.Threading.CancellationToken)
  commentId: M:Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync(System.Threading.CancellationToken)
  id: GetVersionAsync(System.Threading.CancellationToken)
  parent: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient
  langs:
  - csharp
  - vb
  name: GetVersionAsync(CancellationToken)
  nameWithType: IEnvironmentClient.GetVersionAsync(CancellationToken)
  fullName: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync(System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/Picturepark.SDK.V1.CloudManager/Generated/Contracts.Generated.cs
      branch: release-prep/PP9-21763-regenerate-docs
      repo: https://github.com/Picturepark/Picturepark.SDK.DotNet
    id: GetVersionAsync
    path: ../../src/Picturepark.SDK.V1.CloudManager/Generated/Contracts.Generated.cs
    startLine: 792
  assemblies:
  - Picturepark.SDK.V1.CloudManager
  namespace: Picturepark.SDK.V1.CloudManager.Contract
  example: []
  syntax:
    content: Task<VersionInfo> GetVersionAsync(CancellationToken cancellationToken = default)
    parameters:
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: A cancellation token that can be used by other objects or threads to receive notice of cancellation.
    return:
      type: System.Threading.Tasks.Task{Picturepark.SDK.V1.CloudManager.Contract.VersionInfo}
    content.vb: Function GetVersionAsync(cancellationToken As CancellationToken = Nothing) As Task(Of VersionInfo)
  overload: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync*
  exceptions:
  - type: Picturepark.SDK.V1.CloudManager.Contract.ApiException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.ApiException
    description: A server side error occurred.
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
    description: Validation exception
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
    description: Forbidden
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
    description: Version conflict
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
    description: Too many requests
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    description: Internal server error
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
    description: Entity not found
  - type: Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
    commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
    description: Entity not found
references:
- uid: Picturepark.SDK.V1.CloudManager.Contract
  commentId: N:Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.html
  name: Picturepark.SDK.V1.CloudManager.Contract
  nameWithType: Picturepark.SDK.V1.CloudManager.Contract
  fullName: Picturepark.SDK.V1.CloudManager.Contract
  spec.csharp:
  - uid: Picturepark
    name: Picturepark
    href: Picturepark.html
  - name: .
  - uid: Picturepark.SDK
    name: SDK
    href: Picturepark.SDK.html
  - name: .
  - uid: Picturepark.SDK.V1
    name: V1
    href: Picturepark.SDK.V1.html
  - name: .
  - uid: Picturepark.SDK.V1.CloudManager
    name: CloudManager
    href: Picturepark.SDK.V1.CloudManager.html
  - name: .
  - uid: Picturepark.SDK.V1.CloudManager.Contract
    name: Contract
    href: Picturepark.SDK.V1.CloudManager.Contract.html
  spec.vb:
  - uid: Picturepark
    name: Picturepark
    href: Picturepark.html
  - name: .
  - uid: Picturepark.SDK
    name: SDK
    href: Picturepark.SDK.html
  - name: .
  - uid: Picturepark.SDK.V1
    name: V1
    href: Picturepark.SDK.V1.html
  - name: .
  - uid: Picturepark.SDK.V1.CloudManager
    name: CloudManager
    href: Picturepark.SDK.V1.CloudManager.html
  - name: .
  - uid: Picturepark.SDK.V1.CloudManager.Contract
    name: Contract
    href: Picturepark.SDK.V1.CloudManager.Contract.html
- uid: Picturepark.SDK.V1.CloudManager.Contract.ApiException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.ApiException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.ApiException.html
  name: ApiException
  nameWithType: ApiException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.ApiException
- uid: Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException.html
  name: PictureparkValidationException
  nameWithType: PictureparkValidationException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.PictureparkValidationException
- uid: Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException.html
  name: PictureparkForbiddenException
  nameWithType: PictureparkForbiddenException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.PictureparkForbiddenException
- uid: Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException.html
  name: PictureparkConflictException
  nameWithType: PictureparkConflictException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.PictureparkConflictException
- uid: Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException.html
  name: PictureparkTooManyRequestsException
  nameWithType: PictureparkTooManyRequestsException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.PictureparkTooManyRequestsException
- uid: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException.html
  name: PictureparkException
  nameWithType: PictureparkException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.PictureparkException
- uid: Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
  commentId: T:Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
  parent: Picturepark.SDK.V1.CloudManager.Contract
  href: Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException.html
  name: PictureparkNotFoundException
  nameWithType: PictureparkNotFoundException
  fullName: Picturepark.SDK.V1.CloudManager.Contract.PictureparkNotFoundException
- uid: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync*
  commentId: Overload:Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync
  href: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.html#Picturepark_SDK_V1_CloudManager_Contract_IEnvironmentClient_CreateAsync_System_Threading_CancellationToken_
  name: CreateAsync
  nameWithType: IEnvironmentClient.CreateAsync
  fullName: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.CreateAsync
- uid: System.Threading.CancellationToken
  commentId: T:System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration}
  commentId: T:System.Threading.Tasks.Task{Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<EnvironmentConfiguration>
  nameWithType: Task<EnvironmentConfiguration>
  fullName: System.Threading.Tasks.Task<Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration>
  nameWithType.vb: Task(Of EnvironmentConfiguration)
  fullName.vb: System.Threading.Tasks.Task(Of Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration)
  name.vb: Task(Of EnvironmentConfiguration)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration
    name: EnvironmentConfiguration
    href: Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration.html
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration
    name: EnvironmentConfiguration
    href: Picturepark.SDK.V1.CloudManager.Contract.EnvironmentConfiguration.html
  - name: )
- uid: System.Threading
  commentId: N:System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading
  nameWithType: System.Threading
  fullName: System.Threading
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync*
  commentId: Overload:Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync
  href: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.html#Picturepark_SDK_V1_CloudManager_Contract_IEnvironmentClient_GetVersionAsync_System_Threading_CancellationToken_
  name: GetVersionAsync
  nameWithType: IEnvironmentClient.GetVersionAsync
  fullName: Picturepark.SDK.V1.CloudManager.Contract.IEnvironmentClient.GetVersionAsync
- uid: System.Threading.Tasks.Task{Picturepark.SDK.V1.CloudManager.Contract.VersionInfo}
  commentId: T:System.Threading.Tasks.Task{Picturepark.SDK.V1.CloudManager.Contract.VersionInfo}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<VersionInfo>
  nameWithType: Task<VersionInfo>
  fullName: System.Threading.Tasks.Task<Picturepark.SDK.V1.CloudManager.Contract.VersionInfo>
  nameWithType.vb: Task(Of VersionInfo)
  fullName.vb: System.Threading.Tasks.Task(Of Picturepark.SDK.V1.CloudManager.Contract.VersionInfo)
  name.vb: Task(Of VersionInfo)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Picturepark.SDK.V1.CloudManager.Contract.VersionInfo
    name: VersionInfo
    href: Picturepark.SDK.V1.CloudManager.Contract.VersionInfo.html
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Picturepark.SDK.V1.CloudManager.Contract.VersionInfo
    name: VersionInfo
    href: Picturepark.SDK.V1.CloudManager.Contract.VersionInfo.html
  - name: )
